// Autumn — DO_ACTIONS catalog.
// Enumerates the 30 actions the Commander can emit (see 14-renderer-canvas.md §2).
// Used for type-safe execution on the client.

export const DO_ACTIONS = [
  "add_screen",
  "add_chat",
  "add_agents",
  "add_terminal",
  "add_note",
  "add_remotion",
  "add_browser",
  "connect_nodes",
  "disconnect_nodes",
  "rename_node",
  "move_node",
  "remove_node",
  "remove_nodes",
  "arrange_nodes",
  "send_to_node",
  "focus_node",
  "reload_screen",
  "cancel_node",
  "start_dev_server",
  "stop_dev_server",
  "go_home",
  "open_settings",
  "show_canvas",
  "open_finder",
  "find_files",
  "import_sessions",
  "expand_chat",
  "set_auto_comm",
  "set_chat_option",
  "generate_variants",
] as const;

export type DoAction = (typeof DO_ACTIONS)[number];

export const ACTION_DESCRIPTIONS: Record<DoAction, string> = {
  add_screen: "Add a preview screen (desktop or phone).",
  add_chat: "Spawn a named AI agent (chat node).",
  add_agents: "Spawn N agents at once.",
  add_terminal: "Add a terminal node.",
  add_note: "Drop a sticky note.",
  add_remotion: "Add a Remotion video editor node.",
  add_browser: "Add an embedded browser node.",
  connect_nodes: "Wire two nodes with a bus edge.",
  disconnect_nodes: "Remove the bus edge between two nodes.",
  rename_node: "Rename a node.",
  move_node: "Move a node to a new position.",
  remove_node: "Remove a single node.",
  remove_nodes: "Remove nodes by kind or ids.",
  arrange_nodes: "Auto-arrange the canvas.",
  send_to_node: "Send a verbatim task to a chat node.",
  focus_node: "Focus the canvas on a node.",
  reload_screen: "Reload a screen node.",
  cancel_node: "Cancel a running agent.",
  start_dev_server: "Start the dev server.",
  stop_dev_server: "Stop the dev server.",
  go_home: "Navigate to home.",
  open_settings: "Open settings.",
  show_canvas: "Show the canvas.",
  open_finder: "Open the file finder.",
  find_files: "Find files matching a query.",
  import_sessions: "Import prior agent sessions.",
  expand_chat: "Expand a chat node to fullscreen.",
  set_auto_comm: "Toggle auto-commit.",
  set_chat_option: "Update a chat node's options.",
  generate_variants: "Generate UI variants.",
};
